# Generated by Django 5.1.4 on 2025-01-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinventory',
            name='cars_value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
    ]
